spring.application.name=backend
server.port=${PORT:8080}
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima
app.cors.allowed-origins=${APP_FRONTEND_URL}

# CONEXIÓN SQL POSTGRESQL CLOUD
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# CONEXIÓN NOSQL MONGODB CLOUD
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=${MONGO_DB_NAME}

# CONEXIÓN INFERENCIA MODELOS
ai.inference.url=${HF_INFERENCE_URL}
ai.inference.token=${HF_TOKEN}

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=3

spring.servlet.multipart.max-file-size=4MB
spring.servlet.multipart.max-request-size=5MB

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}

# Backups
app.backup.b2-key-id=${B2_KEY_ID}
app.backup.b2-app-key=${B2_APP_KEY}
app.backup.b2-bucket=${B2_BUCKET_NAME}
app.backup.b2-endpoint=${B2_ENDPOINT}
app.backup.encryption-key=${BACKUP_ENCRYPTION_KEY}

# Github Actions
app.github.token=${GITHUB_TOKEN}
app.github.owner=${GITHUB_OWNER}
app.github.repo=${GITHUB_REPO}

app.backup.notify-secret=${BACKUP_NOTIFY_SECRET}
app.backup.cron-secret=${BACKUP_CRON_SECRET}

app.email.dispatch.key-hex=${EMAIL_DISPATCH_KEY_HEX}
app.email.webhook.secret=${EMAIL_WEBHOOK_SECRET}
app.public.api.base-url=${PUBLIC_API_BASE_URL}

app.maintenance.secret=${MAINTENANCE_SECRET}
